/// LLM client module: generating alert text via an OpenAI-compatible API.
///
/// Wraps the `rust-llm-client` crate, which speaks the OpenAI Chat Completions
/// wire format. The provider is selected by `cfg.llm_base_url` (Mistral by
/// default, but Ollama/OpenAI/Groq/OpenRouter work by changing the URL).
/// Text is taken from `choices[0].message.content` by the crate.
///
/// The prompt passes raw numbers (URL, slot delta, RTT, thresholds) to the LLM
/// and requests a concise technical alert ≤ 200 characters, plain text, no markdown.
use rust_llm_client::LlmClient as InnerClient;
use rust_llm_client::{ChatRequest, RetryPolicy};
use tracing::debug;

use crate::analysis::Analysis;
use crate::config::Config;
use crate::error::SentinelError;

/// Client for the OpenAI-compatible Chat Completions API.
///
/// Wraps a `rust_llm_client::LlmClient` configured once from `Config`. The
/// inner client is cheap to clone and reuses its HTTP connection pool.
pub struct LlmClient {
    inner: InnerClient,
}

impl LlmClient {
    /// Builds a client from configuration. Call once at application startup.
    ///
    /// Reads `base_url`/`api_key`/`model` from `cfg` and uses the sentinel retry
    /// profile (4 attempts → 1s, 2s, 4s backoff).
    ///
    /// # Errors
    /// - `SentinelError::LlmClient` — invalid `base_url` or other build failure
    pub fn new(cfg: &Config) -> Result<Self, SentinelError> {
        let mut builder = InnerClient::builder()
            .base_url(&cfg.llm_base_url)
            .model(&cfg.llm_model)
            .retry(RetryPolicy::attempts(4));

        // An empty key means a keyless provider (e.g. local Ollama): omit
        // `.api_key()` so no `Authorization` header is sent.
        if !cfg.llm_api_key.is_empty() {
            builder = builder.api_key(&cfg.llm_api_key);
        }

        let inner = builder.build()?;
        Ok(Self { inner })
    }

    /// Generates a short alert text from analysis data.
    ///
    /// # Arguments
    /// * `target_url` — URL of the monitored node (for context in the prompt)
    /// * `analysis`   — analysis result with slot delta and RTT
    /// * `cfg`        — configuration: thresholds used to build the prompt
    ///
    /// # Returns
    /// A string ≤ 200 characters — the alert text generated by the LLM.
    ///
    /// # Errors
    /// - `SentinelError::LlmClient` — transport error, non-success HTTP status,
    ///   or a response without usable text content
    pub async fn generate_alert_text(
        &self,
        target_url: &str,
        analysis: &Analysis,
        cfg: &Config,
    ) -> Result<String, SentinelError> {
        let prompt = build_prompt(target_url, analysis, cfg);

        debug!(
            model = cfg.llm_model,
            base_url = cfg.llm_base_url,
            "sending request to LLM"
        );

        let text = self
            .inner
            .chat(
                ChatRequest::new()
                    .user(prompt)
                    .max_tokens(256)
                    .temperature(0.2),
            )
            .await?
            .into_text()?
            .trim()
            .to_string();

        debug!(chars = text.len(), "alert generated");

        Ok(text)
    }
}

/// Builds the LLM prompt from analysis data.
///
/// The prompt is in Russian so the LLM responds in the same language.
/// Violated conditions are listed explicitly to keep the alert precise.
fn build_prompt(target_url: &str, analysis: &Analysis, cfg: &Config) -> String {
    // Build the list of violated conditions
    let mut issues = Vec::new();
    if analysis.is_slot_lagging {
        issues.push(format!(
            "отставание слотов: {} (порог: {})",
            analysis.slot_delta, cfg.slot_lag_threshold
        ));
    }
    if analysis.is_rtt_high {
        issues.push(format!(
            "высокий RTT: {}ms (порог: {}ms)",
            analysis.target_rtt_ms, cfg.rtt_threshold_ms
        ));
    }

    format!(
        "Ты — система мониторинга Solana-ноды. Зафиксирован инцидент.\n\
        Нода: {target_url}\n\
        Проблемы: {issues}\n\n\
        Напиши краткий технический алерт на русском языке.\n\
        Требования: максимум 200 символов, только текст, без markdown, без emoji.",
        issues = issues.join("; ")
    )
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    fn make_config() -> Config {
        Config {
            target_rpc_url: "http://localhost:8899".to_string(),
            reference_rpc_url: "https://api.mainnet-beta.solana.com".to_string(),
            poll_interval: Duration::from_secs(10),
            slot_lag_threshold: 5,
            rtt_threshold_ms: 500,
            alert_cooldown: Duration::from_secs(300),
            llm_api_key: "test-key".to_string(),
            llm_model: "mistral-small-latest".to_string(),
            llm_base_url: "https://api.mistral.ai/v1".to_string(),
            telegram_bot_token: "test-token".to_string(),
            telegram_chat_id: "test-chat".to_string(),
        }
    }

    fn make_analysis(slot_delta: i64, target_rtt_ms: u64) -> Analysis {
        Analysis {
            slot_delta,
            target_rtt_ms,
            reference_rtt_ms: 50,
            is_slot_lagging: slot_delta < -5,
            is_rtt_high: target_rtt_ms > 500,
            needs_alert: slot_delta < -5 || target_rtt_ms > 500,
        }
    }

    #[test]
    fn test_prompt_contains_url() {
        let cfg = make_config();
        let analysis = make_analysis(-10, 200);
        let prompt = build_prompt("http://my-node:8899", &analysis, &cfg);
        assert!(prompt.contains("http://my-node:8899"));
    }

    #[test]
    fn test_prompt_contains_slot_issue() {
        let cfg = make_config();
        let analysis = make_analysis(-10, 200);
        let prompt = build_prompt("http://my-node:8899", &analysis, &cfg);
        assert!(prompt.contains("отставание слотов"));
        assert!(prompt.contains("-10"));
    }

    #[test]
    fn test_prompt_contains_rtt_issue() {
        let cfg = make_config();
        let analysis = make_analysis(0, 800);
        let prompt = build_prompt("http://my-node:8899", &analysis, &cfg);
        assert!(prompt.contains("высокий RTT"));
        assert!(prompt.contains("800ms"));
    }

    #[test]
    fn test_prompt_contains_both_issues() {
        let cfg = make_config();
        let analysis = make_analysis(-20, 1200);
        let prompt = build_prompt("http://my-node:8899", &analysis, &cfg);
        assert!(prompt.contains("отставание слотов"));
        assert!(prompt.contains("высокий RTT"));
    }

    /// Live integration test: real Mistral API call.
    /// Run with: cargo test llm_live -- --ignored --nocapture
    #[tokio::test]
    #[ignore]
    async fn test_llm_live() {
        dotenvy::dotenv().ok();

        let cfg = Config {
            target_rpc_url: "http://localhost:8899".to_string(),
            reference_rpc_url: "https://api.mainnet-beta.solana.com".to_string(),
            poll_interval: Duration::from_secs(10),
            slot_lag_threshold: 5,
            rtt_threshold_ms: 500,
            alert_cooldown: Duration::from_secs(300),
            llm_api_key: std::env::var("LLM_API_KEY").expect("LLM_API_KEY не задан"),
            llm_model: std::env::var("LLM_MODEL")
                .unwrap_or_else(|_| "mistral-small-latest".to_string()),
            llm_base_url: std::env::var("LLM_BASE_URL")
                .unwrap_or_else(|_| "https://api.mistral.ai/v1".to_string()),
            telegram_bot_token: "placeholder".to_string(),
            telegram_chat_id: "placeholder".to_string(),
        };

        let analysis = make_analysis(-15, 800);
        let client = LlmClient::new(&cfg).expect("не удалось создать LLM-клиент");
        let text = client
            .generate_alert_text("http://my-node:8899", &analysis, &cfg)
            .await
            .expect("LLM вернул ошибку");

        println!("Сгенерированный алерт:\n{text}");
        assert!(!text.is_empty(), "алерт не должен быть пустым");
        assert!(
            text.len() <= 300,
            "алерт слишком длинный: {} символов",
            text.len()
        );
    }
}
