/// Notifications module: sending messages via the Telegram Bot API.
///
/// Uses the sendMessage method:
/// - Endpoint: POST https://api.telegram.org/bot{token}/sendMessage
/// - parse_mode: "HTML" — safe with special characters in node URLs (< > & etc.)
///
/// On send error — logs via tracing::error! and returns Err.
/// The daemon does not panic and continues running (handled at the alert level).
///
/// The Telegram endpoint is treated as untrusted: every request is bounded by a
/// timeout and every response body by a byte cap, both supplied by `crate::net`,
/// so a hostile or MITM'd peer cannot stall the monitoring loop or exhaust memory.
use reqwest::Client;
use serde_json::json;
use tracing::{debug, error};

use crate::config::Config;
use crate::error::SentinelError;
use crate::net;
use crate::utils;

/// Upper bound on a Telegram response body. Real `sendMessage` replies are well
/// under a kilobyte; anything approaching this cap is a hostile peer trying to
/// exhaust memory, not a legitimate answer.
const MAX_RESPONSE_BYTES: usize = net::MAX_RESPONSE_BYTES;

/// HTTP client for the Telegram Bot API.
///
/// Holds a `reqwest::Client` for connection reuse.
pub struct TelegramClient {
    http: Client,
}

impl TelegramClient {
    /// Creates a new client. Call once at application startup.
    ///
    /// # Errors
    /// - `SentinelError::Http` — the underlying TLS/resolver backend failed to
    ///   initialise, which is a startup fault rather than a per-request one.
    pub fn new() -> Result<Self, SentinelError> {
        let http = net::build_client(net::DEFAULT_REQUEST_TIMEOUT, net::DEFAULT_CONNECT_TIMEOUT)?;

        Ok(Self { http })
    }

    /// Sends a text message to the Telegram chat specified in the configuration.
    ///
    /// # Arguments
    /// * `text` — message text (already generated by the LLM)
    /// * `cfg`  — configuration: bot token, chat_id
    ///
    /// # Errors
    /// - `SentinelError::Http`     — network error or timeout
    /// - `SentinelError::MalformedResponse` — oversized or non-JSON response body
    /// - `SentinelError::Telegram` — Telegram API returned `ok: false`
    pub async fn send_message(&self, text: &str, cfg: &Config) -> Result<(), SentinelError> {
        let url = format!(
            "https://api.telegram.org/bot{}/sendMessage",
            cfg.telegram_bot_token
        );

        let body = json!({
            "chat_id": cfg.telegram_chat_id,
            "text": text,
            // HTML allows <b>, <i> tags and handles special characters in node URLs
            // without additional escaping
            "parse_mode": "HTML"
        });

        debug!(
            chat_id = cfg.telegram_chat_id,
            "sending message to Telegram"
        );

        let http = self.http.clone();

        let response: serde_json::Value = utils::retry_async("telegram api", 3, || {
            let http = http.clone();
            let url = url.clone();
            let b = body.clone();
            async move {
                let response = http
                    .post(url)
                    .json(&b)
                    .send()
                    .await
                    .map_err(SentinelError::Http)?;

                net::read_json_capped(response, MAX_RESPONSE_BYTES).await
            }
        })
        .await?;

        // Telegram returns {"ok": true, ...} on success
        // or {"ok": false, "description": "..."} on error
        if response["ok"].as_bool() != Some(true) {
            let description = response["description"]
                .as_str()
                .unwrap_or("unknown error")
                .to_string();
            error!(
                chat_id = cfg.telegram_chat_id,
                error = description,
                "failed to send Telegram message"
            );
            return Err(SentinelError::Telegram(description));
        }

        debug!("message sent successfully");

        Ok(())
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::net::tests::response_with;
    use std::time::Duration;

    #[tokio::test]
    async fn test_telegram_reply_is_read_under_the_cap() {
        // The send path reads through `net::read_json_capped`; an oversized
        // reply from the bot API is refused before it can be buffered.
        let body = vec![b'x'; MAX_RESPONSE_BYTES + 1];
        let err = net::read_json_capped(response_with(body, true), MAX_RESPONSE_BYTES)
            .await
            .expect_err("an oversized Telegram body must be refused");

        assert!(matches!(err, SentinelError::MalformedResponse(_)));
    }

    #[tokio::test]
    async fn test_a_normal_telegram_ack_survives_the_capped_read() {
        let body = br#"{"ok":true,"result":{"message_id":1}}"#.to_vec();
        let value = net::read_json_capped(response_with(body, true), MAX_RESPONSE_BYTES)
            .await
            .expect("a well-formed ack must parse");

        assert_eq!(value["ok"].as_bool(), Some(true));
    }

    #[test]
    fn test_client_is_built_with_bounded_timeouts() {
        // The constructor must not hand back a client that can hang forever.
        assert!(TelegramClient::new().is_ok());
        assert!(net::DEFAULT_REQUEST_TIMEOUT > Duration::ZERO);
        assert!(net::DEFAULT_CONNECT_TIMEOUT <= net::DEFAULT_REQUEST_TIMEOUT);
    }

    /// Live integration test: real Telegram send.
    /// Run with: cargo test telegram_live -- --ignored --nocapture
    #[tokio::test]
    #[ignore]
    async fn test_telegram_live() {
        dotenvy::dotenv().ok();

        let cfg = Config {
            target_rpc_url: "http://localhost:8899".to_string(),
            reference_rpc_url: "https://api.mainnet-beta.solana.com".to_string(),
            poll_interval: Duration::from_secs(10),
            slot_lag_threshold: 5,
            rtt_threshold_ms: 500,
            alert_cooldown: Duration::from_secs(300),
            llm_api_key: "placeholder".to_string(),
            llm_model: "mistral-small-latest".to_string(),
            llm_base_url: "https://api.mistral.ai/v1".to_string(),
            telegram_bot_token: std::env::var("TELEGRAM_BOT_TOKEN")
                .expect("TELEGRAM_BOT_TOKEN не задан"),
            telegram_chat_id: std::env::var("TELEGRAM_CHAT_ID").expect("TELEGRAM_CHAT_ID не задан"),
        };

        let client = TelegramClient::new().expect("не удалось создать Telegram-клиент");
        client
            .send_message("Тест solana-cli-sentinel: Telegram-клиент работает.", &cfg)
            .await
            .expect("Ошибка отправки в Telegram");

        println!("Сообщение отправлено успешно");
    }
}
